spring.application.name=backend
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.platfrom=psql
spring.jpa.hibernate.ddl-auto=update
# Expose the upload directory as a static resource
spring.web.resources.static-locations=file:///C:/EmpireHotel/
spring.mvc.static-path-pattern=/uploads/**


